In [2]:
import numpy as np

**72. How to swap two rows of an array?** 

In [10]:
#printing array
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
print('the orginal array :')
print(arr)
#swaping array
new_arr =arr[[0,1,2]]=arr[[1,2,0]]
print('the swaped array')
print(new_arr)

the orginal array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the swaped array
[[4 5 6]
 [7 8 9]
 [1 2 3]]


**75. How to compute averages using a sliding window over an array?**

In [17]:
#defining cumilative sum for calculation
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
#printing moving average
moving_average(np.arange(10),2)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5])